# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KetQua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diemthi', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('makhoa', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tenkhoa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('malop', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tenlop', models.CharField(max_length=100)),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Khoa')),
            ],
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('mamh', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tenmh', models.CharField(max_length=100)),
                ('sotiet', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('masv', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=100)),
                ('gioitinh', models.CharField(default='Nam', max_length=3)),
                ('ngaysinh', models.DateField(blank=True, null=True)),
                ('hocbong', models.BooleanField(default=False)),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Lop')),
            ],
        ),
        migrations.AddField(
            model_name='monhoc',
            name='sinhvien',
            field=models.ManyToManyField(through='rest.KetQua', to='rest.SinhVien'),
        ),
        migrations.AddField(
            model_name='ketqua',
            name='monhoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.MonHoc'),
        ),
        migrations.AddField(
            model_name='ketqua',
            name='sinhvien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.SinhVien'),
        ),
    ]
