# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lop',
            name='khoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lop', to='rest.Khoa'),
        ),
    ]
