# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20160625_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinhvien', to='rest.Lop'),
        ),
    ]
