# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20160625_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketqua',
            name='monhoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monhoc', to='rest.MonHoc'),
        ),
        migrations.AlterField(
            model_name='ketqua',
            name='sinhvien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinhvien', to='rest.SinhVien'),
        ),
    ]
